# Generated by Django 6.0.3 on 2026-04-08 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_order_email_order_gateway_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Women', 'Women'), ('Men', 'Men'), ('Kids', 'Kids'), ('Home', 'Home'), ('Perfume', 'Perfume')], default='Women', max_length=50),
        ),
    ]
