# Generated by Django 6.0.3 on 2026-04-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='accessory_type',
            field=models.CharField(blank=True, choices=[('Shoes', 'Shoes'), ('Watches', 'Watches'), ('Glasses', 'Glasses'), ('Belts', 'Belts'), ('Wallets', 'Wallets'), ('Purse', 'Purse'), ('Jewellery', 'Jewellery'), ('Skin-Care', 'Skin-Care')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, choices=[('Men', 'Men'), ('Women', 'Women')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Women', 'Women'), ('Men', 'Men'), ('Kids', 'Kids'), ('Home', 'Accessories'), ('Perfume', 'Perfume')], default='Women', max_length=50),
        ),
    ]
