# Generated by Django 6.0.3 on 2026-04-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_accessory_type_product_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('Shirts', 'Shirts'), ('T-Shirts', 'T-Shirts'), ('Jeans', 'Jeans'), ('Formal', 'Formal'), ('Polos', 'Polos'), ('Jackets', 'Jackets'), ('Trousers', 'Trousers'), ('Dresses', 'Dresses'), ('Tops', 'Tops'), ('Kurtas', 'Kurtas'), ('Sarees', 'Sarees'), ('Skirts', 'Skirts'), ('Co-ords', 'Co-ords'), ('Leggings', 'Leggings'), ('Boys Wear', 'Boys Wear'), ('Girls Wear', 'Girls Wear'), ('Sets', 'Sets'), ('Nightwear', 'Nightwear'), ('Baby Wear', 'Baby Wear')], max_length=50, null=True),
        ),
    ]
