# Generated by Django 6.0.3 on 2026-04-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_product_stock_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_on_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_percent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
